package utils

import configuration.AppSettings

import scala.util.Try

/**
  * Created by Administrator on 2018/4/24.
  */
object etlSource {
  def main(args: Array[String]): Unit = {
    val hiveContext= AppSettings.setConf()

    import hiveContext.implicits._
    hiveContext.sql("use tengxun")
    hiveContext.read.textFile("advertising/userFeature.data").map(line=>{
      val fileds=getdata(line).split(",")
      (fileds(0),fileds(1),fileds(2),fileds(3),fileds(4),fileds(5),fileds(6),fileds(7),fileds(8),fileds(9),fileds(10),fileds(11),fileds(12),fileds(13),fileds(14),fileds(15),fileds(16),fileds(17),fileds(18),fileds(19),fileds(20),fileds(21)+"_"+fileds(22))
    }).toDF("uid","age","gender","marriagestatus" ,"education","consumptionability","lbs","interest1","interest2","interest3","interest4","interest5","kw1","kw2","kw3","topic1","topic2","topic3","appidinstall","ct","os","carrier")
      .createOrReplaceTempView("source2")
    hiveContext.sql(
      """
        |create table sourcelot(
        | uid                 	string,
        | age                 	string,
        | gender              	string,
        | marriagestatus      	string,
        | education           	string,
        | consumptionability  	string,
        | lbs                 	string,
        | interest1_1           string,
        | interest1_2           string,
        | interest1_3           string,
        | interest1_4           string,
        | interest1_5           string,
        | interest1_6          string,
        | interest1_7           string,
        | interest1_8           string,
        | interest1_9           string,
        | interest1_10           string,
        | interest1_11           string,
        | interest1_12           string,
        | interest1_13           string,
        | interest1_14           string,
        | interest1_15           string,
        | interest1_16           string,
        | interest1_17           string,
        | interest1_18           string,
        | interest1_19           string,
        | interest1_20           string,
        | interest2_1           	string,
        | interest2_2           	string,
        | interest2_3           	string,
        | interest2_4           	string,
        | interest2_5           	string,
        | interest2_6            	string,
        | interest2_7            	string,
        | interest2_8            	string,
        | interest2_9            	string,
        | interest2_10           	string,
        | interest2_11           	string,
        | interest2_12           	string,
        | interest2_13           	string,
        | interest2_14           	string,
        | interest2_15           	string,
        | interest2_16           	string,
        | interest2_17           	string,
        | interest2_18           	string,
        | interest2_19           	string,
        | interest2_20           	string,
        | interest3_1           	string,
        | interest3_2           	string,
        | interest3_3           	string,
        | interest3_4           	string,
        | interest3_5           	string,
        | interest3_6            	string,
        | interest3_7            	string,
        | interest3_8            	string,
        | interest3_9            	string,
        | interest3_10           	string,
        | interest3_11           	string,
        | interest3_12           	string,
        | interest3_13           	string,
        | interest3_14           	string,
        | interest3_15           	string,
        | interest3_16           	string,
        | interest3_17           	string,
        | interest3_18           	string,
        | interest3_19           	string,
        | interest3_20           	string,
        | interest4_1           	string,
        | interest4_2           	string,
        | interest4_3           	string,
        | interest4_4           	string,
        | interest4_5           	string,
        | interest4_6            	string,
        | interest4_7            	string,
        | interest4_8            	string,
        | interest4_9            	string,
        | interest4_10           	string,
        | interest4_11           	string,
        | interest4_12           	string,
        | interest4_13           	string,
        | interest4_14           	string,
        | interest4_15           	string,
        | interest4_16           	string,
        | interest4_17           	string,
        | interest4_18           	string,
        | interest4_19           	string,
        | interest4_20           	string,
        | interest5_1         	  string,
        | interest5_2         	  string,
        | interest5_3         	  string,
        | interest5_4         	  string,
        | interest5_5         	  string,
        | interest5_6          	  string,
        | interest5_7          	  string,
        | interest5_8          	  string,
        | interest5_9          	  string,
        | interest5_10         	  string,
        | interest5_11         	  string,
        | interest5_12         	  string,
        | interest5_13         	  string,
        | interest5_14         	  string,
        | interest5_15         	  string,
        | interest5_16         	  string,
        | interest5_17         	  string,
        | interest5_18         	  string,
        | interest5_19         	  string,
        | interest5_20         	  string,
        | kw1_1                 	string,
        | kw1_2                 	string,
        | kw1_3                 	string,
        | kw1_4                 	string,
        | kw1_5                 	string,
        | kw1_6                  	string,
        | kw1_7                  	string,
        | kw1_8                  	string,
        | kw1_9                  	string,
        | kw1_10                 	string,
        | kw1_11                 	string,
        | kw1_12                 	string,
        | kw1_13                 	string,
        | kw1_14                 	string,
        | kw1_15                 	string,
        | kw1_16                 	string,
        | kw1_17                 	string,
        | kw1_18                 	string,
        | kw1_19                 	string,
        | kw1_20                 	string,
        | kw2_1                 	string,
        | kw2_2                 	string,
        | kw2_3                 	string,
        | kw2_4                 	string,
        | kw2_5                 	string,
        | kw2_6                  	string,
        | kw2_7                  	string,
        | kw2_8                  	string,
        | kw2_9                  	string,
        | kw2_10                 	string,
        | kw2_11                 	string,
        | kw2_12                 	string,
        | kw2_13                 	string,
        | kw2_14                 	string,
        | kw2_15                 	string,
        | kw2_16                 	string,
        | kw2_17                 	string,
        | kw2_18                 	string,
        | kw2_19                 	string,
        | kw2_20                 	string,
        | kw3_1                 	string,
        | kw3_2                 	string,
        | kw3_3                 	string,
        | kw3_4                 	string,
        | kw3_5                 	string,
        | kw3_6                  	string,
        | kw3_7                  	string,
        | kw3_8                  	string,
        | kw3_9                  	string,
        | kw3_10                 	string,
        | kw3_11                 	string,
        | kw3_12                 	string,
        | kw3_13                 	string,
        | kw3_14                 	string,
        | kw3_15                 	string,
        | kw3_16                 	string,
        | kw3_17                 	string,
        | kw3_18                 	string,
        | kw3_19                 	string,
        | kw3_20                 	string,
        | topic1_1              	string,
        | topic1_2              	string,
        | topic1_3              	string,
        | topic1_4              	string,
        | topic1_5              	string,
        | topic1_6               string,
        | topic1_7               string,
        | topic1_8               string,
        | topic1_9               string,
        | topic1_10              string,
        | topic1_11              string,
        | topic1_12              string,
        | topic1_13              string,
        | topic1_14              string,
        | topic1_15              string,
        | topic1_16              string,
        | topic1_17              string,
        | topic1_18              string,
        | topic1_19              string,
        | topic1_20              string,
        | topic2_1               	string,
        | topic2_2               	string,
        | topic2_3               	string,
        | topic2_4               	string,
        | topic2_5               	string,
        | topic2_6               string,
        | topic2_7               string,
        | topic2_8               string,
        | topic2_9               string,
        | topic2_10              string,
        | topic2_11              string,
        | topic2_12              string,
        | topic2_13              string,
        | topic2_14              string,
        | topic2_15              string,
        | topic2_16              string,
        | topic2_17              string,
        | topic2_18              string,
        | topic2_19              string,
        | topic2_20              string,
        | topic3_1              	string,
        | topic3_2              	string,
        | topic3_3              	string,
        | topic3_4              	string,
        | topic3_5              	string,
        | topic3_6               string,
        | topic3_7               string,
        | topic3_8               string,
        | topic3_9               string,
        | topic3_10              string,
        | topic3_11              string,
        | topic3_12              string,
        | topic3_13              string,
        | topic3_14              string,
        | topic3_15              string,
        | topic3_16              string,
        | topic3_17              string,
        | topic3_18              string,
        | topic3_19              string,
        | topic3_20              string,
        | appidinstall           string,
        | ct                  	 string,
        | os                  	 string,
        | carrier             	 string,
        | house                  string
        |)
      """.stripMargin)
    hiveContext.sql(
      """
        | insert into table sourcelot
        | select
        | uid               ,
        | age               ,
        | gender            ,
        | marriagestatus    ,
        | education         ,
        | consumptionability,
        | lbs               ,
        | split(interest1,'#')[0],
        | split(interest1,'#')[1],
        | split(interest1,'#')[2],
        | split(interest1,'#')[3],
        | split(interest1,'#')[4],
        | split(interest1,'#')[5],
        | split(interest1,'#')[6],
        | split(interest1,'#')[7],
        | split(interest1,'#')[8],
        | split(interest1,'#')[9],
        | split(interest1,'#')[10],
        | split(interest1,'#')[11],
        | split(interest1,'#')[12],
        | split(interest1,'#')[13],
        | split(interest1,'#')[14],
        | split(interest1,'#')[15],
        | split(interest1,'#')[16],
        | split(interest1,'#')[17],
        | split(interest1,'#')[18],
        | split(interest1,'#')[19],
        | split(interest2,'#')[0],
        | split(interest2,'#')[1],
        | split(interest2,'#')[2],
        | split(interest2,'#')[3],
        | split(interest2,'#')[4],
        | split(interest2,'#')[5],
        | split(interest2,'#')[6],
        | split(interest2,'#')[7],
        | split(interest2,'#')[8],
        | split(interest2,'#')[9],
        | split(interest2,'#')[10],
        | split(interest2,'#')[11],
        | split(interest2,'#')[12],
        | split(interest2,'#')[13],
        | split(interest2,'#')[14],
        | split(interest2,'#')[15],
        | split(interest2,'#')[16],
        | split(interest2,'#')[17],
        | split(interest2,'#')[18],
        | split(interest2,'#')[19],
        | split(interest3,'#')[0],
        | split(interest3,'#')[1],
        | split(interest3,'#')[2],
        | split(interest3,'#')[3],
        | split(interest3,'#')[4],
        | split(interest3,'#')[5],
        | split(interest3,'#')[6],
        | split(interest3,'#')[7],
        | split(interest3,'#')[8],
        | split(interest3,'#')[9],
        | split(interest3,'#')[10],
        | split(interest3,'#')[11],
        | split(interest3,'#')[12],
        | split(interest3,'#')[13],
        | split(interest3,'#')[14],
        | split(interest3,'#')[15],
        | split(interest3,'#')[16],
        | split(interest3,'#')[17],
        | split(interest3,'#')[18],
        | split(interest3,'#')[19],
        | split(interest4,'#')[0],
        | split(interest4,'#')[1],
        | split(interest4,'#')[2],
        | split(interest4,'#')[3],
        | split(interest4,'#')[4],
        | split(interest4,'#')[5],
        | split(interest4,'#')[6],
        | split(interest4,'#')[7],
        | split(interest4,'#')[8],
        | split(interest4,'#')[9],
        | split(interest4,'#')[10],
        | split(interest4,'#')[11],
        | split(interest4,'#')[12],
        | split(interest4,'#')[13],
        | split(interest4,'#')[14],
        | split(interest4,'#')[15],
        | split(interest4,'#')[16],
        | split(interest4,'#')[17],
        | split(interest4,'#')[18],
        | split(interest4,'#')[19],
        | split(interest5,'#')[0],
        | split(interest5,'#')[1],
        | split(interest5,'#')[2],
        | split(interest5,'#')[3],
        | split(interest5,'#')[4],
        | split(interest5,'#')[5],
        | split(interest5,'#')[6],
        | split(interest5,'#')[7],
        | split(interest5,'#')[8],
        | split(interest5,'#')[9],
        | split(interest5,'#')[10],
        | split(interest5,'#')[11],
        | split(interest5,'#')[12],
        | split(interest5,'#')[13],
        | split(interest5,'#')[14],
        | split(interest5,'#')[15],
        | split(interest5,'#')[16],
        | split(interest5,'#')[17],
        | split(interest5,'#')[18],
        | split(interest5,'#')[19],
        | split(kw1,'#')[0],
        | split(kw1,'#')[1],
        | split(kw1,'#')[2],
        | split(kw1,'#')[3],
        | split(kw1,'#')[4],
        | split(kw1,'#')[5],
        | split(kw1,'#')[6],
        | split(kw1,'#')[7],
        | split(kw1,'#')[8],
        | split(kw1,'#')[9],
        | split(kw1,'#')[10],
        | split(kw1,'#')[11],
        | split(kw1,'#')[12],
        | split(kw1,'#')[13],
        | split(kw1,'#')[14],
        | split(kw1,'#')[15],
        | split(kw1,'#')[16],
        | split(kw1,'#')[17],
        | split(kw1,'#')[18],
        | split(kw1,'#')[19],
        | split(kw2,'#')[0],
        | split(kw2,'#')[1],
        | split(kw2,'#')[2],
        | split(kw2,'#')[3],
        | split(kw2,'#')[4],
        | split(kw2,'#')[5],
        | split(kw2,'#')[6],
        | split(kw2,'#')[7],
        | split(kw2,'#')[8],
        | split(kw2,'#')[9],
        | split(kw2,'#')[10],
        | split(kw2,'#')[11],
        | split(kw2,'#')[12],
        | split(kw2,'#')[13],
        | split(kw2,'#')[14],
        | split(kw2,'#')[15],
        | split(kw2,'#')[16],
        | split(kw2,'#')[17],
        | split(kw2,'#')[18],
        | split(kw2,'#')[19],
        | split(kw3,'#')[0],
        | split(kw3,'#')[1],
        | split(kw3,'#')[2],
        | split(kw3,'#')[3],
        | split(kw3,'#')[4],
        | split(kw3,'#')[5],
        | split(kw3,'#')[6],
        | split(kw3,'#')[7],
        | split(kw3,'#')[8],
        | split(kw3,'#')[9],
        | split(kw3,'#')[10],
        | split(kw3,'#')[11],
        | split(kw3,'#')[12],
        | split(kw3,'#')[13],
        | split(kw3,'#')[14],
        | split(kw3,'#')[15],
        | split(kw3,'#')[16],
        | split(kw3,'#')[17],
        | split(kw3,'#')[18],
        | split(kw3,'#')[19],
        | split(topic1,'#')[0],
        | split(topic1,'#')[1],
        | split(topic1,'#')[2],
        | split(topic1,'#')[3],
        | split(topic1,'#')[4],
        | split(topic1,'#')[5],
        | split(topic1,'#')[6],
        | split(topic1,'#')[7],
        | split(topic1,'#')[8],
        | split(topic1,'#')[9],
        | split(topic1,'#')[10],
        | split(topic1,'#')[11],
        | split(topic1,'#')[12],
        | split(topic1,'#')[13],
        | split(topic1,'#')[14],
        | split(topic1,'#')[15],
        | split(topic1,'#')[16],
        | split(topic1,'#')[17],
        | split(topic1,'#')[18],
        | split(topic1,'#')[19],
        | split(topic2,'#')[0],
        | split(topic2,'#')[1],
        | split(topic2,'#')[2],
        | split(topic2,'#')[3],
        | split(topic2,'#')[4],
        | split(topic2,'#')[5],
        | split(topic2,'#')[6],
        | split(topic2,'#')[7],
        | split(topic2,'#')[8],
        | split(topic2,'#')[9],
        | split(topic2,'#')[10],
        | split(topic2,'#')[11],
        | split(topic2,'#')[12],
        | split(topic2,'#')[13],
        | split(topic2,'#')[14],
        | split(topic2,'#')[15],
        | split(topic2,'#')[16],
        | split(topic2,'#')[17],
        | split(topic2,'#')[18],
        | split(topic2,'#')[19],
        | split(topic3,'#')[0],
        | split(topic3,'#')[1],
        | split(topic3,'#')[2],
        | split(topic3,'#')[3],
        | split(topic3,'#')[4],
        | split(topic3,'#')[5],
        | split(topic3,'#')[6],
        | split(topic3,'#')[7],
        | split(topic3,'#')[8],
        | split(topic3,'#')[9],
        | split(topic3,'#')[10],
        | split(topic3,'#')[11],
        | split(topic3,'#')[12],
        | split(topic3,'#')[13],
        | split(topic3,'#')[14],
        | split(topic3,'#')[15],
        | split(topic3,'#')[16],
        | split(topic3,'#')[17],
        | split(topic3,'#')[18],
        | split(topic3,'#')[19],
        | appidinstall      ,
        | ct                ,
        | os                ,
        | split(carrier,'_')[0],
        | split(carrier,'_')[1]
        | from source2
      """.stripMargin)
  }
  def getdata(columnNames : String): String = {
    var value = "uid$,age$,gender$,marriagestatus$ ,education$,consumptionabiltity$,lbs$,interest1$,interest2$,interest3$,interest4$,interest5$,kw1$,kw2$,kw3$,topic1$,topic2$,topic3$,appidinstall$,ct$,os$,carrier$,house$"
    for (col <- columnNames.split("\\|")) {
      if (col.contains((" "))) {
        val kv = col.split(" ")
        val colName = col.split(' ')(0) + "$"
        var colValues = col.split(' ')
        val colValue = new StringBuilder()
        if (colName.contains("interest")||colName.contains("kw")||colName.contains("topic")){
          for (i <- 0 to colValues.length - 1) {
            if (i != 0) {
              if (i == colValues.length - 1) {
                colValue.append(colValues(i))
              } else {
                colValue.append(colValues(i) + "#")
              }
            }

          }
        }else {
          colValue.append(colValues(1))
        }
        value= value.replace(colName.toLowerCase(),colValue.toString())
        colValue.clear()
      }
    }

    var result =""
    value.split(',').foreach(x=> (result= result + ","+ toLongs(x)))
    result.substring(1)

  }
  def toLongs(s: String): String = {
    val reguler="^[0-9]"
    if(s.matches(s)){
      s
    }else{
      "0"
    }
  }

}
